// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/gw-gong/boilerplate-go/internal/app/svc02/svc/test01"
	"github.com/gw-gong/boilerplate-go/internal/app/svc02/svc/test02"
	"github.com/gw-gong/boilerplate-go/internal/config/svc02/localcfg"
	"github.com/gw-gong/gwkit-go/grpc/consul"
	"github.com/gw-gong/gwkit-go/hotcfg"
)

// Injectors from wire.go:

func InitRpcServer(cfgOption *hotcfg.LocalConfigOption) (*RpcServer, func(), error) {
	config, err := localcfg.NewConfig(cfgOption)
	if err != nil {
		return nil, nil, err
	}
	hotLoaderManager := hotcfg.NewHotLoaderManager()
	agentAddr := config.ConsulAgentAddr
	consulClient, err := consul.NewConsulClient(agentAddr)
	if err != nil {
		return nil, nil, err
	}
	test01Svc := test01.NewTest01Svc()
	test02Svc := test02.NewTest02Svc()
	rpcServer := &RpcServer{
		cfg:          config,
		hlm:          hotLoaderManager,
		consulClient: consulClient,
		test01Svc:    test01Svc,
		test02Svc:    test02Svc,
	}
	return rpcServer, func() {
	}, nil
}

// wire.go:

var ConfigSet = wire.NewSet(localcfg.NewConfig, wire.FieldsOf(
	new(*localcfg.Config),
	"ConsulAgentAddr",
), hotcfg.NewHotLoaderManager,
)

var InfraSet = wire.NewSet(consul.NewConsulClient)

var BizSet = wire.NewSet(test01.NewTest01Svc, test02.NewTest02Svc)

var RpcServerSet = wire.NewSet(wire.Struct(new(RpcServer), "*"))
