// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gw-gong/go-template-project/internal/app/svc02/svc/test01"
	"github.com/gw-gong/go-template-project/internal/app/svc02/svc/test02"
	"github.com/gw-gong/go-template-project/internal/config/svc02/localcfg"
)

// Injectors from wire.go:

func InitRpcServer(config *localcfg.Config) (*RpcServer, func(), error) {
	test01Svc := test01.NewTest01Svc()
	test02Svc := test02.NewTest02Svc()
	rpcServer := &RpcServer{
		cfg:       config,
		test01Svc: test01Svc,
		test02Svc: test02Svc,
	}
	return rpcServer, func() {
	}, nil
}
