// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/gw-gong/boilerplate-go/internal/app/svc01/router"
	"github.com/gw-gong/boilerplate-go/internal/config/svc01/localcfg"
	"github.com/gw-gong/boilerplate-go/internal/config/svc01/netcfg"
	"github.com/gw-gong/boilerplate-go/internal/pkg/biz/biz01"
	"github.com/gw-gong/boilerplate-go/internal/pkg/biz/biz02"
	"github.com/gw-gong/boilerplate-go/internal/pkg/client/rpc/svc02"
	"github.com/gw-gong/boilerplate-go/internal/pkg/db/mysql"
	"github.com/gw-gong/boilerplate-go/internal/pkg/util/provider"
	"github.com/gw-gong/gwkit-go/grpc/consul"
	"github.com/gw-gong/gwkit-go/hotcfg"
)

// Injectors from wire.go:

func InitHttpServer(cfgOption *hotcfg.LocalConfigOption) (*HttpServer, func(), error) {
	config, err := localcfg.NewConfig(cfgOption)
	if err != nil {
		return nil, nil, err
	}
	consulConfigOption := config.ConsulNetCfg
	netcfgConfig, err := netcfg.NewConfig(consulConfigOption)
	if err != nil {
		return nil, nil, err
	}
	hotLoaderManager := hotcfg.NewHotLoaderManager()
	engine := provider.NewGinEngine()
	biz01Options := config.Biz01
	biz01Biz01 := biz01.NewBiz01(biz01Options)
	biz02Options := config.Biz02
	biz02Biz02, cleanup := biz02.NewBiz02(biz02Options)
	test01DbManagerOptions := netcfgConfig.Test01DbManager
	test01DbManager, err := mysql.NewTest01DbManager(test01DbManagerOptions)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	test02DbManagerOptions := netcfgConfig.Test02DbManager
	test02DbManager, err := mysql.NewTest02DbManager(test02DbManagerOptions)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	agentAddr := config.ConsulAgentAddr
	consulClient, err := consul.NewConsulClient(agentAddr)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	test01ClientOption := config.Test01Client
	test01Client, err := svc02.NewTest01Client(consulClient, test01ClientOption)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	test02ClientOption := config.Test02Client
	test02Client, err := svc02.NewTest02Client(consulClient, test02ClientOption)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	apiRouter := &router.ApiRouter{
		Biz01:           biz01Biz01,
		Biz02:           biz02Biz02,
		Test01DbManager: test01DbManager,
		Test02DbManager: test02DbManager,
		Test01Client:    test01Client,
		Test02Client:    test02Client,
	}
	appRouter := &router.AppRouter{
		Biz01:           biz01Biz01,
		Biz02:           biz02Biz02,
		Test01DbManager: test01DbManager,
		Test02DbManager: test02DbManager,
	}
	portalRouter := &router.PortalRouter{
		Biz01:           biz01Biz01,
		Biz02:           biz02Biz02,
		Test01DbManager: test01DbManager,
		Test02DbManager: test02DbManager,
	}
	privateRouter := &router.PrivateRouter{
		Biz01:           biz01Biz01,
		Biz02:           biz02Biz02,
		Test01DbManager: test01DbManager,
		Test02DbManager: test02DbManager,
	}
	httpServer := &HttpServer{
		localCfg:      config,
		netCfg:        netcfgConfig,
		hlm:           hotLoaderManager,
		router:        engine,
		apiRouter:     apiRouter,
		appRouter:     appRouter,
		portalRouter:  portalRouter,
		privateRouter: privateRouter,
	}
	return httpServer, func() {
		cleanup()
	}, nil
}

// wire.go:

var ConfigSet = wire.NewSet(localcfg.NewConfig, wire.FieldsOf(
	new(*localcfg.Config),
	"ConsulAgentAddr",
	"ConsulNetCfg",
	"Biz01",
	"Biz02",
	"Test01Client",
	"Test02Client",
), netcfg.NewConfig, wire.FieldsOf(
	new(*netcfg.Config),
	"Test01DbManager",
	"Test02DbManager",
), hotcfg.NewHotLoaderManager,
)

var InfraSet = wire.NewSet(provider.NewGinEngine, mysql.NewTest01DbManager, mysql.NewTest02DbManager, consul.NewConsulClient, svc02.NewTest01Client, svc02.NewTest02Client)

var BizSet = wire.NewSet(biz01.NewBiz01, biz02.NewBiz02)

var RouterSet = wire.NewSet(wire.Struct(new(router.ApiRouter), "*"), wire.Struct(new(router.AppRouter), "*"), wire.Struct(new(router.PortalRouter), "*"), wire.Struct(new(router.PrivateRouter), "*"))

var HttpServerSet = wire.NewSet(wire.Struct(new(HttpServer), "*"))
