// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gw-gong/go-template-project/internal/app/svc01/router"
	"github.com/gw-gong/go-template-project/internal/config/svc01/localcfg"
	"github.com/gw-gong/go-template-project/internal/config/svc01/netcfg"
	"github.com/gw-gong/go-template-project/internal/pkg/biz/biz01"
	"github.com/gw-gong/go-template-project/internal/pkg/biz/biz02"
	"github.com/gw-gong/go-template-project/internal/pkg/client/rpc/svc02"
	"github.com/gw-gong/go-template-project/internal/pkg/db/mysql"
)

// Injectors from wire.go:

func InitHttpServer(config *localcfg.Config, netCfg *netcfg.Config) (*HttpServer, func(), error) {
	biz01Options := config.Biz01
	biz01Biz01 := biz01.NewBiz01(biz01Options)
	biz02Options := config.Biz02
	biz02Biz02, cleanup := biz02.NewBiz02(biz02Options)
	test01DbManagerOptions := netCfg.Test01DbManager
	test01DbManager, err := mysql.NewTest01DbManager(test01DbManagerOptions)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	test02DbManagerOptions := netCfg.Test02DbManager
	test02DbManager, err := mysql.NewTest02DbManager(test02DbManagerOptions)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	test01ClientOption := config.Test01Client
	test01Client, err := svc02.NewTest01Client(test01ClientOption)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	test02ClientOption := config.Test02Client
	test02Client, err := svc02.NewTest02Client(test02ClientOption)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	apiRouter := &router.ApiRouter{
		Biz01:           biz01Biz01,
		Biz02:           biz02Biz02,
		Test01DbManager: test01DbManager,
		Test02DbManager: test02DbManager,
		Test01Client:    test01Client,
		Test02Client:    test02Client,
	}
	appRouter := &router.AppRouter{
		Biz01:           biz01Biz01,
		Biz02:           biz02Biz02,
		Test01DbManager: test01DbManager,
		Test02DbManager: test02DbManager,
	}
	portalRouter := &router.PortalRouter{
		Biz01:           biz01Biz01,
		Biz02:           biz02Biz02,
		Test01DbManager: test01DbManager,
		Test02DbManager: test02DbManager,
	}
	privateRouter := &router.PrivateRouter{
		Biz01:           biz01Biz01,
		Biz02:           biz02Biz02,
		Test01DbManager: test01DbManager,
		Test02DbManager: test02DbManager,
	}
	httpServer := &HttpServer{
		cfg:           config,
		netCfg:        netCfg,
		apiRouter:     apiRouter,
		appRouter:     appRouter,
		portalRouter:  portalRouter,
		privateRouter: privateRouter,
	}
	return httpServer, func() {
		cleanup()
	}, nil
}
