// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gw-gong/template_project/internal/app/service01/router"
	"github.com/gw-gong/template_project/internal/pkg/components/component01"
	"github.com/gw-gong/template_project/internal/pkg/components/component02"
	"github.com/gw-gong/template_project/internal/pkg/db/mysql"
)

// Injectors from wire.go:

func InitHttpServer(ctx context.Context, component01erOptions component01.Component01erOptions, component02erOptions component02.Component02erOptions) (*httpServer, func(), error) {
	component01er := component01.NewComponent01er(component01erOptions)
	component02er, cleanup := component02.NewComponent02er(component02erOptions)
	xxxDbManager := mysql.NewXxxDbManager()
	apiRouter := &router.ApiRouter{
		Component01er: component01er,
		Component02er: component02er,
		XxxDbManager:  xxxDbManager,
	}
	mainHttpServer := &httpServer{
		ctx:       ctx,
		apiRouter: apiRouter,
	}
	return mainHttpServer, func() {
		cleanup()
	}, nil
}
