// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/gw-gong/go-template-project/config/local_config/service01"
	"github.com/gw-gong/go-template-project/internal/app/service01/router"
	"github.com/gw-gong/go-template-project/internal/pkg/components/component01"
	"github.com/gw-gong/go-template-project/internal/pkg/components/component02"
	"github.com/gw-gong/go-template-project/internal/pkg/db/mysql"
)

// Injectors from wire.go:

func InitHttpServer(ctx context.Context, config *service01.Config) (*httpServer, func(), error) {
	component01Options := config.Component01
	component01Component01 := component01.NewComponent01(component01Options)
	component02Options := config.Component02
	component02Component02, cleanup := component02.NewComponent02(component02Options)
	xxxDbManager := mysql.NewXxxDbManager()
	apiRouter := &router.ApiRouter{
		Component01:  component01Component01,
		Component02:  component02Component02,
		XxxDbManager: xxxDbManager,
	}
	appRouter := &router.AppRouter{
		Component01:  component01Component01,
		Component02:  component02Component02,
		XxxDbManager: xxxDbManager,
	}
	portalRouter := &router.PortalRouter{
		Component01:  component01Component01,
		Component02:  component02Component02,
		XxxDbManager: xxxDbManager,
	}
	privateRouter := &router.PrivateRouter{
		Component01:  component01Component01,
		Component02:  component02Component02,
		XxxDbManager: xxxDbManager,
	}
	mainHttpServer := &httpServer{
		ctx:           ctx,
		cfg:           config,
		apiRouter:     apiRouter,
		appRouter:     appRouter,
		portalRouter:  portalRouter,
		privateRouter: privateRouter,
	}
	return mainHttpServer, func() {
		cleanup()
	}, nil
}
