// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.2
// source: test_service.proto

package svc02

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test01Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field01       string                 `protobuf:"bytes,1,opt,name=field01,proto3" json:"field01,omitempty"`
	Field02       string                 `protobuf:"bytes,2,opt,name=field02,proto3" json:"field02,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test01Request) Reset() {
	*x = Test01Request{}
	mi := &file_test_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test01Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test01Request) ProtoMessage() {}

func (x *Test01Request) ProtoReflect() protoreflect.Message {
	mi := &file_test_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test01Request.ProtoReflect.Descriptor instead.
func (*Test01Request) Descriptor() ([]byte, []int) {
	return file_test_service_proto_rawDescGZIP(), []int{0}
}

func (x *Test01Request) GetField01() string {
	if x != nil {
		return x.Field01
	}
	return ""
}

func (x *Test01Request) GetField02() string {
	if x != nil {
		return x.Field02
	}
	return ""
}

type Test01Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field01       string                 `protobuf:"bytes,1,opt,name=field01,proto3" json:"field01,omitempty"`
	Field02       string                 `protobuf:"bytes,2,opt,name=field02,proto3" json:"field02,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test01Response) Reset() {
	*x = Test01Response{}
	mi := &file_test_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test01Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test01Response) ProtoMessage() {}

func (x *Test01Response) ProtoReflect() protoreflect.Message {
	mi := &file_test_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test01Response.ProtoReflect.Descriptor instead.
func (*Test01Response) Descriptor() ([]byte, []int) {
	return file_test_service_proto_rawDescGZIP(), []int{1}
}

func (x *Test01Response) GetField01() string {
	if x != nil {
		return x.Field01
	}
	return ""
}

func (x *Test01Response) GetField02() string {
	if x != nil {
		return x.Field02
	}
	return ""
}

type Test02Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field01       string                 `protobuf:"bytes,1,opt,name=field01,proto3" json:"field01,omitempty"`
	Field02       string                 `protobuf:"bytes,2,opt,name=field02,proto3" json:"field02,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test02Request) Reset() {
	*x = Test02Request{}
	mi := &file_test_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test02Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test02Request) ProtoMessage() {}

func (x *Test02Request) ProtoReflect() protoreflect.Message {
	mi := &file_test_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test02Request.ProtoReflect.Descriptor instead.
func (*Test02Request) Descriptor() ([]byte, []int) {
	return file_test_service_proto_rawDescGZIP(), []int{2}
}

func (x *Test02Request) GetField01() string {
	if x != nil {
		return x.Field01
	}
	return ""
}

func (x *Test02Request) GetField02() string {
	if x != nil {
		return x.Field02
	}
	return ""
}

type Test02Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field01       string                 `protobuf:"bytes,1,opt,name=field01,proto3" json:"field01,omitempty"`
	Field02       string                 `protobuf:"bytes,2,opt,name=field02,proto3" json:"field02,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test02Response) Reset() {
	*x = Test02Response{}
	mi := &file_test_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test02Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test02Response) ProtoMessage() {}

func (x *Test02Response) ProtoReflect() protoreflect.Message {
	mi := &file_test_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test02Response.ProtoReflect.Descriptor instead.
func (*Test02Response) Descriptor() ([]byte, []int) {
	return file_test_service_proto_rawDescGZIP(), []int{3}
}

func (x *Test02Response) GetField01() string {
	if x != nil {
		return x.Field01
	}
	return ""
}

func (x *Test02Response) GetField02() string {
	if x != nil {
		return x.Field02
	}
	return ""
}

var File_test_service_proto protoreflect.FileDescriptor

const file_test_service_proto_rawDesc = "" +
	"\n" +
	"\x12test_service.proto\"C\n" +
	"\rTest01Request\x12\x18\n" +
	"\afield01\x18\x01 \x01(\tR\afield01\x12\x18\n" +
	"\afield02\x18\x02 \x01(\tR\afield02\"D\n" +
	"\x0eTest01Response\x12\x18\n" +
	"\afield01\x18\x01 \x01(\tR\afield01\x12\x18\n" +
	"\afield02\x18\x02 \x01(\tR\afield02\"C\n" +
	"\rTest02Request\x12\x18\n" +
	"\afield01\x18\x01 \x01(\tR\afield01\x12\x18\n" +
	"\afield02\x18\x02 \x01(\tR\afield02\"D\n" +
	"\x0eTest02Response\x12\x18\n" +
	"\afield01\x18\x01 \x01(\tR\afield01\x12\x18\n" +
	"\afield02\x18\x02 \x01(\tR\afield022>\n" +
	"\rTest01Service\x12-\n" +
	"\bTestFunc\x12\x0e.Test01Request\x1a\x0f.Test01Response\"\x002>\n" +
	"\rTest02Service\x12-\n" +
	"\bTestFunc\x12\x0e.Test02Request\x1a\x0f.Test02Response\"\x00B\tZ\a.;svc02b\x06proto3"

var (
	file_test_service_proto_rawDescOnce sync.Once
	file_test_service_proto_rawDescData []byte
)

func file_test_service_proto_rawDescGZIP() []byte {
	file_test_service_proto_rawDescOnce.Do(func() {
		file_test_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_service_proto_rawDesc), len(file_test_service_proto_rawDesc)))
	})
	return file_test_service_proto_rawDescData
}

var file_test_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_test_service_proto_goTypes = []any{
	(*Test01Request)(nil),  // 0: Test01Request
	(*Test01Response)(nil), // 1: Test01Response
	(*Test02Request)(nil),  // 2: Test02Request
	(*Test02Response)(nil), // 3: Test02Response
}
var file_test_service_proto_depIdxs = []int32{
	0, // 0: Test01Service.TestFunc:input_type -> Test01Request
	2, // 1: Test02Service.TestFunc:input_type -> Test02Request
	1, // 2: Test01Service.TestFunc:output_type -> Test01Response
	3, // 3: Test02Service.TestFunc:output_type -> Test02Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_service_proto_init() }
func file_test_service_proto_init() {
	if File_test_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_service_proto_rawDesc), len(file_test_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_test_service_proto_goTypes,
		DependencyIndexes: file_test_service_proto_depIdxs,
		MessageInfos:      file_test_service_proto_msgTypes,
	}.Build()
	File_test_service_proto = out.File
	file_test_service_proto_goTypes = nil
	file_test_service_proto_depIdxs = nil
}
