// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: test_service.proto

package svc02

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Test01Service_TestFunc_FullMethodName = "/Test01Service/TestFunc"
)

// Test01ServiceClient is the client API for Test01Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Test01ServiceClient interface {
	TestFunc(ctx context.Context, in *Test01Request, opts ...grpc.CallOption) (*Test01Response, error)
}

type test01ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTest01ServiceClient(cc grpc.ClientConnInterface) Test01ServiceClient {
	return &test01ServiceClient{cc}
}

func (c *test01ServiceClient) TestFunc(ctx context.Context, in *Test01Request, opts ...grpc.CallOption) (*Test01Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Test01Response)
	err := c.cc.Invoke(ctx, Test01Service_TestFunc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Test01ServiceServer is the server API for Test01Service service.
// All implementations must embed UnimplementedTest01ServiceServer
// for forward compatibility.
type Test01ServiceServer interface {
	TestFunc(context.Context, *Test01Request) (*Test01Response, error)
	mustEmbedUnimplementedTest01ServiceServer()
}

// UnimplementedTest01ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTest01ServiceServer struct{}

func (UnimplementedTest01ServiceServer) TestFunc(context.Context, *Test01Request) (*Test01Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestFunc not implemented")
}
func (UnimplementedTest01ServiceServer) mustEmbedUnimplementedTest01ServiceServer() {}
func (UnimplementedTest01ServiceServer) testEmbeddedByValue()                       {}

// UnsafeTest01ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Test01ServiceServer will
// result in compilation errors.
type UnsafeTest01ServiceServer interface {
	mustEmbedUnimplementedTest01ServiceServer()
}

func RegisterTest01ServiceServer(s grpc.ServiceRegistrar, srv Test01ServiceServer) {
	// If the following call pancis, it indicates UnimplementedTest01ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Test01Service_ServiceDesc, srv)
}

func _Test01Service_TestFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test01Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Test01ServiceServer).TestFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Test01Service_TestFunc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Test01ServiceServer).TestFunc(ctx, req.(*Test01Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Test01Service_ServiceDesc is the grpc.ServiceDesc for Test01Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Test01Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Test01Service",
	HandlerType: (*Test01ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestFunc",
			Handler:    _Test01Service_TestFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test_service.proto",
}

const (
	Test02Service_TestFunc_FullMethodName = "/Test02Service/TestFunc"
)

// Test02ServiceClient is the client API for Test02Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Test02ServiceClient interface {
	TestFunc(ctx context.Context, in *Test02Request, opts ...grpc.CallOption) (*Test02Response, error)
}

type test02ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTest02ServiceClient(cc grpc.ClientConnInterface) Test02ServiceClient {
	return &test02ServiceClient{cc}
}

func (c *test02ServiceClient) TestFunc(ctx context.Context, in *Test02Request, opts ...grpc.CallOption) (*Test02Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Test02Response)
	err := c.cc.Invoke(ctx, Test02Service_TestFunc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Test02ServiceServer is the server API for Test02Service service.
// All implementations must embed UnimplementedTest02ServiceServer
// for forward compatibility.
type Test02ServiceServer interface {
	TestFunc(context.Context, *Test02Request) (*Test02Response, error)
	mustEmbedUnimplementedTest02ServiceServer()
}

// UnimplementedTest02ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTest02ServiceServer struct{}

func (UnimplementedTest02ServiceServer) TestFunc(context.Context, *Test02Request) (*Test02Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestFunc not implemented")
}
func (UnimplementedTest02ServiceServer) mustEmbedUnimplementedTest02ServiceServer() {}
func (UnimplementedTest02ServiceServer) testEmbeddedByValue()                       {}

// UnsafeTest02ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Test02ServiceServer will
// result in compilation errors.
type UnsafeTest02ServiceServer interface {
	mustEmbedUnimplementedTest02ServiceServer()
}

func RegisterTest02ServiceServer(s grpc.ServiceRegistrar, srv Test02ServiceServer) {
	// If the following call pancis, it indicates UnimplementedTest02ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Test02Service_ServiceDesc, srv)
}

func _Test02Service_TestFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test02Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Test02ServiceServer).TestFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Test02Service_TestFunc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Test02ServiceServer).TestFunc(ctx, req.(*Test02Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Test02Service_ServiceDesc is the grpc.ServiceDesc for Test02Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Test02Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Test02Service",
	HandlerType: (*Test02ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestFunc",
			Handler:    _Test02Service_TestFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test_service.proto",
}
